### ISSUE TITLE
Message Modifier Issues????

### ISSUE THREAD

**Issue by robnist** [haffo/hit-iz-tool#221]
Weren’t these set by the message modifier?

Sandra, I think we need more checks with regards to the namespace ID and OID.

Are we running the checks each time we deploy?

See both images. For the second one the spec indicates ORC-3 should be NIST-AA-IZ-2 and not 3.

![image](https://cloud.githubusercontent.com/assets/14874904/11578265/d0f4d8ee-99f1-11e5-8b4d-e46e6883a372.png)

![image](https://cloud.githubusercontent.com/assets/14874904/11578266/d6c57418-99f1-11e5-8766-82753c05b5a9.png)

**Comment by sriniadhiwork** [comment]
as discussed, the config files now carry the right mappings [and the tcamt was manually fixed by Rob, so next time we re-run the config it should be correct going forward as well]
ORC-2.2*=NIST-AA-IZ-2
ORC-2.3*=2.16.840.1.113883.3.72.5.40.10
ORC-2.4*=ISO

ORC-3.2*=NIST-AA-IZ-2
ORC-3.3*=2.16.840.1.113883.3.72.5.40.10
ORC-3.4*=ISO

ORC-10.9.1*=NIST-PI-1
ORC-10.9.2*=2.16.840.1.113883.3.72.5.40.7
ORC-10.9.3*=ISO

ORC-12.9.1*=NIST-PI-1
ORC-12.9.2*=2.16.840.1.113883.3.72.5.40.7
ORC-12.9.3*=ISO
