### ISSUE TITLE
Empty fields incorrect validation on CPs

### ISSUE THREAD

**Issue by smartinez290** [haffo/hit-iz-tool#264]
The tool is not validating correctly the CPs when there are empty fields. Take a look at 
the following Z22 message, it is generating an incorrect error when missing RXA-20.

MSH|^~\&|Test EHR Application|X68||NIST Test Iz Reg|20120701082240-0500||VXU^V04^VXU_V04|NIST-IZ-001.00|P|2.5.1|||ER|AL|||||Z22^CDCPHINVS
PID|1||D26376273^^^NIST MPI^MR||Snow^Madelynn^Ainsley^^^^L|Lam^Morgan^^^^^M|20070706|F||2076-8^Native Hawaiian or Other Pacific Islander^CDCREC|32 Prescott Street Ave^^Warwick^MA^02452^USA^L||^PRN^PH^^^657^5558563|||||||||2186-5^non Hispanic or Latino^CDCREC
PD1|||||||||||02^Reminder/Recall - any method^HL70215|||||A|20120701|20120701
NK1|1|Lam^Morgan^^^^^L|MTH^Mother^HL70063|32 Prescott Street Ave^^Warwick^MA^02452^USA^L|^PRN^PH^^^657^5558563
ORC|RE||IZ-783274^NDA|||||||I-23432^Burden^Donna^A^^^^^NIST-AA-1^^^^PRN||57422^RADON^NICHOLAS^^^^^^NIST-AA-1^L^^^MD
RXA|0|1|20160203|20160203|998^No Vaccine Administered^CVX|999
RXR|C28161^Intramuscular^NCIT|LD^Left Arm^HL70163
OBX|1|CE|64994-7^Vaccine funding program eligibility category^LN|1|V05^VFC eligible - Federally Qualified Health Center Patient (under-insured)^HL70064||||||F|||20120701|||VXC40^Eligibility captured at the immunization level^CDCPHINVS
OBX|2|CE|30956-7^vaccine type^LN|2|88^Influenza, unspecified formulation^CVX||||||F
OBX|3|TS|29768-9^Date vaccine information statement published^LN|2|20120702||||||F
OBX|4|TS|29769-7^Date vaccine information statement presented^LN|2|20120814||||||F

**Comment by HossamT** [comment]
Per my email :

I'll explain the problem :
PlainText, StringList, PathValue, NumberList, Format.
 
These constraint all pass if the targeted path is not populated, I can't remember why Salifou has made this choice, I think Caroline can give more information.
 
The problem is at the Predicates level, for example the message above (VXU) triggers a Predicate detection even if RXA-20 is not populated. :
 
The required Field RXA-9 (Administration Notes) is missing. The element is required based on the condition predicate evaluation: If the value of RXA-20 (Completion Status) is one of List Values: 'CP','PA'.
 
I tried some more predicates and it seems that it not only this one that's concerned by this problem.
 
The solution is to always use the "Presence" Constraint "AND" a constraint from the list above. Another solution is to change the validation engine to fail in case the path is not populated but at this stage I'm suspecting it will create conflicts.

@Jungyubw please take a look at IZ constraints and predicates to fix this problem, thank you.

**Comment by smartinez290** [comment]
@Jungyubw please, refresh my mind... did you fix this issue?  If so please move to Waiting for QA.

Thanks.

**Comment by smartinez290** [comment]
@HossamT @Jungyubw @robnist The tool is failing after this fix. Getting CS errors for empty elements. 

![image](https://cloud.githubusercontent.com/assets/14842422/13083806/978b3df8-d4a4-11e5-9048-8dab833d458e.png)

**Comment by Jungyubw** [comment]
Fixed
