### ISSUE TITLE
 WARNINGS for RE elements 

### ISSUE THREAD

**Issue by smartinez290** [haffo/hit-iz-tool#53]
When selecting the check box for the WARNINGS for RE elements a whole lot of stuff gets high-light that is incorrect. For these I guess nothing would get high-lighted unless you would want to insert a string “RE ELEMENT” and high-light that. This is aspect is low priority. ALERTS seems find—maybe this is just an issue when data is missing. For errors, it is highlight what is before and after.

**Comment by smartinez290** [comment]
This is not an UI issue. The validator needs to be more specific in the path that it provides.

**Comment by haffo** [comment]
The tool highlights whatever path is provided by the validator. @HossamT can you look at this. Let me know if any question.

**Comment by HossamT** [comment]
I can't see a better way to do it. RE Warnings mean that an RE element is missing, which means that there is nothing to highlight, the path returned by the validation engine is the path of the nearest existing parent of the missing element. So this should be handled by the UI in order to decide what to do with this path in this case.

**Comment by haffo** [comment]
If an element is missing why are you providing a path then ?

**Comment by haffo** [comment]
Actually can't you provide the actual path of the missing element ?

**Comment by HossamT** [comment]
It's just the way it was done in the validation engine by Salifou, I will see if I can do something about it and get back to you.

**Comment by robnist** [comment]
My thought is that if the path of the missing element is provided, the GUI could insert the string “RE-MISSING” where the element should be when the user checks the RE Missing check box.

I’m sure this is possible to do, but not sure how practical. The original message needs to be maintained when other items are checked. This would only be when the RE Missing is checked.
We can discuss more later today.
Rob

**Comment by haffo** [comment]
The old validator was returning the path of the element missing and the ui points the cursor to the element location in the editor.

**Comment by HossamT** [comment]
Ok, so after analysis, I can actually change the code to return the path of the missing element in this case (and also in the case of a missing R element) which are both part of the Structure Validation. However, as part of the Content Validation, the usage of the Presence Constraint is harder to change in order make the validation engine return the path of the missing element, because : 
- In the case of the structure validation, if an element is missing we have access to it's parent because we check step by step, so we can easily compute the path of the missing parent from its parent. However, when using the Presence Constraint we are looking for a particular element, and chances are that its parents are missing so even if I succeed to compute the path of this element from the context element of the constraint, the GUI would have nowhere to point to.

**Comment by smartinez290** [comment]
@HossamT what is the status on this issue. @robnist do we need further discussion?

**Comment by robnist** [comment]
What was the resolution?

**Comment by smartinez290** [comment]
@HossamT Rob wants to know what was the solution. It looks like the warnings highlights are gone. Per, Rob's request a new ticket will be opened to developed a solution to highlight the pipes where the RE elements are missing.

**Comment by HossamT** [comment]
@robnist @smartinez290 The validation is now returning the exact path of the missing element (For structure validation which means for Usage related issues)
