### ISSUE TITLE
IZ-QR-1_Query_Young_Adult 1.IZ-QR-1.1_Query_Q11_Z44 - Value Set biding issue

### ISSUE THREAD

**Issue by smartinez290** [haffo/hit-iz-tool#98]
RCP[1]-2[1].1
	The value '1' at location Component RCP-2.1 (Quantity) is not member of the value set HL70126_IZ   - 

RCP-2.1 does not have a binding to HL70126_IZ why is the tool validating against that value set?

**Comment by HossamT** [comment]
@Jungyubw @smartinez290 With the new validation engine rules, you can specify VS bindings for Complex Elements. 

In the Z44 Profile RCP-2 it's defined like this : 

<Field Name="Quantity Limited Request" Usage="R" Min="1" Max="1" Datatype="CQ_IZ" MinLength="1" MaxLength="10" Binding="HL70126_IZ" BindingStrength="R" ItemNo="00031" BindingLocation="1"/>

You can see that the Field RCP-2 has a VS binding to HL70126_IZ at location 1. The specification was always there but it wasn't interpreted by the validation engine because it's a Complex Element (Complex Field) ... Now that the feature is implemented it's taken into account by the validation engine.
If the element is not supposed to have a VS binding then the profile should be modified in order to remove the binding from the Field. It's an issue in the profile, I think @Jungyubw should handle that.

**Comment by robnist** [comment]
Seems strange at the RCP-2 level that the binding is there. Looks OK for RCP-2.2.

**Comment by smartinez290** [comment]
@woo will take care of this issue. Thanks.

**Comment by Jungyubw** [comment]
fixed
